### PR TITLE
Run management commands from the project root

### PR DESCRIPTION
**Pull request by marcosmoyano**
Define res in pony-rc to solve problems within Spacemacs and running tests.

@davidmiller please let me know what you think

### CODE REVIEW

**Comment by marcosmoyano** [comment]
--use-mirrors was removed in pip V 7.0.0.

**Comment by gone** [comment]
It would be fantastic if this could get merged

**Comment by marcosmoyano** [comment]
Looks like this is no longer maintained :(
Last commit is from Oct 2015

**Comment by davidmiller** [comment]
Hi @marcosmoyano @gone !

Think I stopped doing Django development as part of my day job around then and work on this has been slow ever since...

I think this PR: https://github.com/davidmiller/pony-mode/pull/99 wound up being expanded to also fix a bug in the same function as this PR, but also e.g. stops calling `--use-mirrors` in Pip.

I suspect it might be worth figuring out if that fixes the issue in `pony-rc` that this PR also addresses and merging in the fix for travis?

**Pull request closed without merging**
